# fly.toml app configuration file generated for tiks-ultimate-rsvp-cron on 2023-09-16T06:32:20+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tiks-ultimate-rsvp-cron"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  cron = "python scripts/cron.py"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = []
  processes = ["cron"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
