#!/usr/bin/env python3
import subprocess
import sys
from urllib.parse import urlparse


def main(mongodb_uri):
    # mongodb_uri = 'mongodb://heroku_cdbwn214:1gnk7hfqe9mvra4srsvfo81fhl@ds233769.mlab.com:33769/heroku_cdbwn214'
    parsed = urlparse(mongodb_uri)
    db = parsed.path.lstrip('/')
    if '@' in parsed.netloc:
        auth, server = parsed.netloc.split('@')
        username, password = auth.split(':')
    else:
        server = parsed.netloc
        username = password = ''
    host, port = server.split(':')
    args = sys.argv[1:]
    for arg in args:
        assert not arg.startswith(
            '-'
        ), 'This script constructs all the options!'
    command = ['alley']
    if db:
        command.extend(['-db', db])
    if host:
        command.extend(['-h', host])
    if port:
        command.extend(['-p', port])
    if username:
        command.extend(['-u', username])
    if password:
        command.extend(['-w', password])
    command.extend(args)
    print('Running command:: {}'.format(' '.join(command)))
    subprocess.check_call(command)


if __name__ == '__main__':
    import os

    mongodb_uri = os.environ.get('MONGODB_URI', '')
    if not mongodb_uri:
        print("You must set MONGODB_URI env var to use this script")
        sys.exit(1)
    main(mongodb_uri)
