#!/usr/bin/env python3
"""Script to update the permissions of a shared GDrive folder

This script uses a service account to manage the permissions of a shared folder
in GDrive. The service account was created from this page:
https://console.developers.google.com/projectselector/iam-admin/serviceaccounts

The credentials of the service account have been saved to a private gist whose
URL has been set as an environment variable. The credentials could potentially
be directly saved as environment variables, but this seemed much more easier to
manage.

*NOTE*: Ensure that the GDrive API has been enabled in the project that this
service account is being used from.

*NOTE*: Ensure that the drive has been (manually) shared with the user of the
 service account, before trying to run this script.

"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from rsvp.models import GDrivePhoto
from rsvp.gdrive_utils import create_service, photos

if __name__ == '__main__':
    service = create_service()
    gdrive_root = os.environ['GOOGLE_DRIVE_MEDIA_DRIVE_ID']
    photos = [GDrivePhoto(**photo) for photo in photos(service, gdrive_root)]
    GDrivePhoto.objects.delete()
    GDrivePhoto.objects.insert(photos)
